site_name: sensOrange Documentation
site_url: https://sensorangerobotics.com
theme: 
  name: material
  custom_dir: docs/overrides/
  favicon: assets/logo.png
  logo: assets/logobig.png
  palette: 
    scheme: slate
    primary: black
    accent: orange
  features:
    search: false
nav: 
- Welcome: index.md
- Encoder: encoder.md
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra_css:
  - assets/sidebar-tweak.css